### ISSUE TITLE
Support d'autres prénoms

### ISSUE THREAD

**Issue by nicmarti** [dgageot/marcel#1]
Bonjour

Envisagez-vous le support d'autres prénoms comme Michel ou Robert ? 

Merci

**Comment by brouberol** [comment]
Cher monsieur,
Ce commentaire fleure la sécession. Est-ce un test?

**Comment by dgageot** [comment]
"Le nom de « débardeur » vient du fait qu'il reproduisait, lors de son adoption par le prêt-à-porter vers 1973, la forme des tricots des dockers." -- wikipedia

docker -> débardeur --> marcel

Alors Michel et Robert sont complètement hors jeu mon cher @nicmarti 
On n'est pas là pour faire n'importe quoi. On parle de mission parlementaire d'intérêt général tout de même
